version: '3.8'

services:
  postiz-app:
    image: postiz-app:onesso-local
    container_name: postiz-app
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - ONESSO_BASE_URL=http://keycloak:8080
      - ONESSO_REALM=postiz-realm
      - ONESSO_CLIENT_ID=postiz-client
      - ONESSO_CLIENT_SECRET=changeme
      - ONESSO_REDIRECT_URI=http://localhost:3000/auth/onesso/callback
    networks:
      - postiz-network
    depends_on:
      - postgres
      - redis
      - keycloak

  postgres:
    image: postgres:14
    container_name: postiz-postgres
    environment:
      - POSTGRES_USER=postiz-local
      - POSTGRES_PASSWORD=postizpass
      - POSTGRES_DB=postiz-db-local
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postiz-network

  redis:
    image: redis:7
    container_name: postiz-redis
    ports:
      - "6379:6379"
    networks:
      - postiz-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=changeme
      - KC_DB=postgres
      - KC_DB_URL_HOST=postiz-postgres
      - KC_DB_USERNAME=postiz-local
      - KC_DB_PASSWORD=postizpass
    ports:
      - "8080:8080"
    command: 
      - start-dev
    networks:
      - postiz-network
    depends_on:
      - postgres

networks:
  postiz-network:
    driver: bridge

volumes:
  postgres-data:
